//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForWaiters {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.ListBox lblMultiSelectOfDishes;
		
		protected System.Web.UI.WebControls.TextBox txtBoxQuantityPierogi;
		
		protected System.Web.UI.WebControls.TextBox txtBoxQuantityZupa;
		
		protected System.Web.UI.WebControls.TextBox txtBoxQuantityZapiekanka;
		
		protected System.Web.UI.WebControls.TextBox txtBoxQuantityLody;
		
		protected System.Web.UI.WebControls.TextBox txtBoxQuantitySzarlotka;
		
		protected System.Web.UI.WebControls.TextBox txtBoxQuantitySok;
		
		protected System.Web.UI.WebControls.ListBox lblMultiSelectOfTables;

        protected System.Web.UI.WebControls.ListBox lblDishesForFirstTable;

        protected System.Web.UI.WebControls.Label labelIdd;
    }
}
